// Nomor WhatsApp untuk tujuan pemesanan
export const whatsappNumber = '6281234567890';

// Ekspor data produk agar bisa diimpor di file lain
export const allProducts = [
  // Keycaps
  {
    id: 'keycaps-01',
    name: 'Nekomech Topographic Engraved',
    category: 'keycaps',
    description: 'Elevate your keyboard with this unique set featuring an intricate topographic engraved design with durable PBT material for a premium feel.',
    price: 199000,
    imageUrl: './public/products/nekomech-keycap.jpeg',
    createdAt: '2025-10-01T10:00:00Z',
  },
  {
    id: 'keycaps-02',
    name: 'Furycube South-facing Contours',
    category: 'keycaps',
    description: 'Illuminate your setup with these futuristic keycaps, designed with translucent legends that are perfect for south-facing RGB keyboards.',
    price: 238900,
    imageUrl: './public/products/furycube-keycap.jpeg',
    createdAt: '2025-09-30T10:00:00Z',
  },
  {
    id: 'keycaps-03',
    name: 'Gundam Unicorn Japanese',
    category: 'keycaps',
    description: 'Showcase your love for mecha anime with this artisan keycap inspired by the iconic Gundam Unicorn, featuring crisp Japanese characters.',
    price: 329000,
    imageUrl: './public/products/gundam-unicorn.jpeg',
    createdAt: '2025-09-29T10:00:00Z',
  },
  // Keyboards
  {
    id: 'keyboard-01',
    name: 'Rexus Heroic KX3',
    category: 'keyboards',
    description: 'A compact 68-key layout with anti-ghosting, dual-tone keycaps, and a detachable USB Type-C cable, perfect for gamers seeking both style and function.',
    price: 290000,
    imageUrl: './public/products/rexus-keyboard.png',
    createdAt: '2025-10-02T10:00:00Z',
  },
  {
    id: 'keyboard-02',
    name: 'Vusign LED Wired Mechanical',
    category: 'keyboards',
    description: 'Features a full-size layout with 7-color LED backlighting, an integrated wrist rest, and multimedia hot-keys for a comfortable experience.',
    price: 219000,
    imageUrl: './public/products/deli-vusign.png',
    createdAt: '2025-09-28T10:00:00Z',
  },
  {
    id: 'keyboard-03',
    name: 'Gamen Titan Pro',
    category: 'keyboards',
    description: 'Built with a durable aluminum frame, a 5-layer gasket structure for quiet typing, and multifunction knob to control RGB lighting and volume.',
    price: 699000,
    imageUrl: './public/products/gamen-titan.png',
    createdAt: '2025-09-27T10:00:00Z',
  },
  // Switches
  {
    id: 'switch-01',
    name: 'Cherry MX Hyperglide',
    category: 'switches',
    description: 'Experience the legendary smoothness of Cherry MX, now upgraded with Hyperglide tooling for reduced friction and enhanced durability.',
    price: 40000,
    imageUrl: './public/products/cherry-mx.png',
    createdAt: '2025-10-03T10:00:00Z',
  },
  {
    id: 'switch-02',
    name: 'C³ Equalz x TKC Tangerine',
    category: 'switches',
    description: 'Famous for their incredibly smooth linear travel and vibrant orange housing. These switches provide a buttery-smooth typing experience.',
    price: 45000,
    imageUrl: './public/products/equalz.png',
    createdAt: '2025-09-26T10:00:00Z',
  },
  {
    id: 'switch-03',
    name: 'Shogoki Tactile',
    category: 'switches',
    description: 'Designed for a satisfying typing feel, these switches offer a sharp and pronounced tactile bump with every keystroke, ensuring precision.',
    price: 39000,
    imageUrl: './public/products/shogoki-switch.png',
    createdAt: '2025-09-25T10:00:00Z',
  },
  // Stabilizers
  {
    id: 'stabilizer-01',
    name: 'MoYu.Studios Screw-In',
    category: 'stabilizers',
    description: 'Precision-engineered screw-in stabilizers designed to minimize rattle and provide a consistent feel for your spacebar and modifier keys.',
    price: 780000,
    imageUrl: './public/products/moyu-stabilizer.png',
    createdAt: '2025-09-24T10:00:00Z',
  },
  {
    id: 'stabilizer-02',
    name: 'TX Stabilizer Rev 3.0',
    category: 'stabilizers',
    description: 'The latest revision of the popular TX stabilizers, featuring a patented doubleshot stem for a tighter fit to reduce wobble and unwanted noise.',
    price: 1750000,
    imageUrl: './public/products/tx-stabilizer.webp',
    createdAt: '2025-09-23T10:00:00Z',
  },
  {
    id: 'stabilizer-03',
    name: 'Lubcon Turmotemp II/400',
    category: 'stabilizers',
    description: 'A premium-grade lubricant ideal for stabilizer wires and housings. This grease effectively eliminates rattle and ensures ultra-smooth operation.',
    price: 40000,
    imageUrl: './public/products/lubcon-stabilizer.png',
    createdAt: '2025-09-22T10:00:00Z',
  },
];